przewodnik_po_miescie/mainapp/urls.py
from django.urls import path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import dodaj_do_koszyka,docs_redirect

urlpatterns = [
    path('', views.main, name='home'),
    path('atrakcje/<int:atrakcja_id>/', views.atrakcja, name='atrakcja'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('koszyk/', views.koszyk, name='koszyk'),
    path('dodaj_do_koszyka/<int:atrakcja_id>/', dodaj_do_koszyka, name='dodaj_do_koszyka'),
    path('dodaj_do_koszyka_home/<int:atrakcja_id>/', views.dodaj_do_koszyka_home, name='dodaj_do_koszyka_home'),
    path('usun_z_koszyka/<int:item_id>/', views.usun_z_koszyka, name='usun_z_koszyka'),
    path('trasa/', views.trasa, name='trasa'),
    path('plany/', views.plany, name='plany'),
    path('plany/<int:plan_id>/', views.pojedynczy_plan, name='pojedynczy_plan'),
    path('pdf_download/', views.pdf_download, name='pdf_download'),
    path('plan_uzytkownika/', views.plan_uzytkownika, name='plan_uzytkownika'),
    path('zapisz_plan/', views.zapisz_plan, name='zapisz_plan'),
    path('usun_z_planu/<int:plan_id>/', views.usun_z_planu, name='usun_z_planu'),
    path('plan_do_koszyka/<int:plan_id>/', views.plan_do_koszyka, name='plan_do_koszyka'),
    path('send_mail/', views.send_mail, name='send_mail'),
    path('docs/', docs_redirect),
]
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT),

przewodnik_po_miescie/przewodnik_po_miescie/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')) ,
    path('', include('mainapp.urls')),
    path('admin/', admin.site.urls),
]

przewodnik_po_miescie/mainapp/models.py
from django.contrib.auth.models import User
from django.db import models
from decimal import Decimal


class Kategorie(models.Model):
    """
    Przechowuje pojedynczą kategorię, która może być przypisana do wielu atrakcji.
    """
    nazwa_kategorii = models.CharField(max_length=50, primary_key=True)


class Atrakcja(models.Model):
    """
    Przechowuje pojedynczą atrakcję, związaną z modelem `Kategorie`.
    """
    nazwa_atrakcji = models.CharField(max_length=50, default="Atrakcja")
    opis = models.TextField(max_length=1100)
    kategoria = models.ForeignKey(Kategorie, on_delete=models.CASCADE)
    cena_podstawowa = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('0.00'))
    wiek_min = models.IntegerField()
    wiek_max = models.IntegerField()
    godzina_otwarcia = models.TimeField()
    godzina_zamkniecia = models.TimeField()
    czas_na_zwiedzanie = models.PositiveIntegerField()
    obraz = models.CharField(max_length=10000, default="")

    def __str__(self):
        return self.nazwa_atrakcji


class Adres_atrakcji(models.Model):
    """
    Przechowuje adres pojedynczej atrakcji, związany z modelem `Atrakcja`.
    """
    id_atrakcji = models.ForeignKey(Atrakcja, on_delete=models.CASCADE)
    kraj = models.CharField(max_length=50)
    miasto = models.CharField(max_length=50)
    kod_pocztowy = models.CharField(max_length=10)
    ulica = models.CharField(max_length=50)
    nr_budynku = models.CharField(max_length=50)
    nr_lokalu = models.CharField(max_length=50)


class Znizka(models.Model):
    """
    Przechowuje pojedynczą zniżkę, która może być stosowana do różnych atrakcji lub planów.
    """
    nazwa_znizki = models.CharField(max_length=30)
    mnoznik = models.DecimalField(max_digits=10, decimal_places=2, default=Decimal('1.00'))

    def __str__(self):
        return self.nazwa_znizki


class Plan(models.Model):
    """
    Przechowuje pojedynczy plan utworzony przez użytkownika, związany z modelem `auth.User` oraz
    wieloma `Atrakcja` przez model `PrzypisanieAtrakcji`.
    """
    id_klienta = models.ForeignKey(User, on_delete=models.CASCADE)
    nazwa_planu = models.CharField(max_length=50)
    opis_planu = models.TextField(max_length=1100)
    atrakcje = models.ManyToManyField(Atrakcja, through="PrzypisanieAtrakcji")
    data_utworzenia = models.DateField()
    obraz = models.CharField(max_length=10000, default="")

    def __str__(self):
        return self.nazwa_planu
    
    def save(self, *args, **kwargs):
        """
        Niestandardowa metoda zapisu obliczająca końcową cenę planu
        na podstawie cen zawartych atrakcji.
        """
        if not self.pk:
            super().save(*args, **kwargs)

        self.cena_koncowa = sum(atrakcja.cena_podstawowa for atrakcja in self.atrakcje.all())
        super().save(*args, **kwargs)


class PrzypisanieAtrakcji(models.Model):
    """
    Model pośredni dla relacji wiele-do-wielu między modelami `Plan` i
    `Atrakcja`.
    """
    atrakcja = models.ForeignKey(Atrakcja, on_delete=models.CASCADE)
    plan = models.ForeignKey(Plan, on_delete=models.CASCADE)


class Koszyk(models.Model):
    """
    Przechowuje pojedynczy przedmiot w koszyku użytkownika, związany z modelami `Atrakcja` i
    `auth.User`.
    """
    id_atrakcji = models.ForeignKey(Atrakcja, on_delete=models.CASCADE)
    id_klienta = models.ForeignKey(User, on_delete=models.CASCADE)
    cena_koncowa = models.DecimalField(max_digits=8, decimal_places=2, default=Decimal('0.00'))
    ilosc = models.IntegerField(default=1)


class PlanyUzytkownika(models.Model):
    id_klienta = models.ForeignKey(User, on_delete=models.CASCADE)
    nazwa_planu_uzytkownika = models.CharField(max_length=50)
    atrakcje = models.ManyToManyField(Atrakcja)
    data_utworzenia = models.DateField()

przewodnik_po_miescie/mainapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Atrakcja, Plan

class LogInForm(forms.Form):
    """
    Formularz logowania użytkownika.
    """
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

class SignUpForm(UserCreationForm):
    """
    Formularz rejestracji użytkownika.
    """
    def __init__(self, *args, **kwargs):
        super(UserCreationForm,self).__init__(*args,**kwargs)

        for fieldname in ["username","password1","password2"]:
            self.fields[fieldname].help_text = None
    class Meta:
        model = User
        fields = ("username","first_name", "last_name", "email", "password1", "password2")
        widgets = {
            'password1': forms.PasswordInput(),
            'password2': forms.PasswordInput(),
        }

    def save(self, commit=True):
        user = super(SignUpForm, self).save(commit=False)
        if commit:
            user.save()
        return user

class StartLocation(forms.Form):
    """
    Formularz wyboru lokalizacji początkowej i trybu podróży.
    """
    start_location = forms.CharField()
    mode_choices = {
        ('driving', 'Pojazd'),
        ('walking', 'Pieszo')
    }
    mode = forms.ChoiceField(choices=mode_choices)

class PlanForm(forms.ModelForm):
    """
    Formularz tworzenia planu podróży.
    """
    atrakcje = forms.ModelMultipleChoiceField(queryset=Atrakcja.objects.all(), widget=forms.CheckboxSelectMultiple)

    class Meta:
        model = Plan
        fields = ['id_klienta', 'nazwa_planu', 'opis_planu', 'atrakcje', 'data_utworzenia', 'obraz']

przewodnik_po_miescie/mainapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import SignUpForm, LogInForm, StartLocation
from .models import Atrakcja, Koszyk, Plan, Znizka, PlanyUzytkownika
from django.http import HttpResponse
from django.contrib import messages
from .maps import generate_static_map, generate_interactive_map
from .pdf import generate_pdf
from io import BytesIO
from django.core.mail import EmailMessage
import os
from django.conf import settings
from django.utils import timezone
import logging
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse


logger = logging.getLogger('mainapp')


def user_signup(request):
    """
    Widok rejestracji użytkownika.

    GET: Wyświetla formularz rejestracji.
    POST: Obsługuje przesłany formularz rejestracji.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    """
    if request.method == 'POST':
        logger.debug("Rozpoczęcie rejestracji użytkownika")
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, 'Pomyślnie zarejestrowano.')
            logger.info(f"Nowy użytkownik zarejestrowany: {form.cleaned_data['username']}")

            return redirect('home')
        else:
            logger.warning(f"Nieudana próba rejestracji: {form.errors}")
    else:
        form = SignUpForm()
    return render(request, 'rejestracja.html', {'form': form})


def user_login(request):
    """
    Widok logowania użytkownika.

    GET: Wyświetla formularz logowania.
    POST: Obsługuje przesłany formularz logowania.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    """
    source = request.GET.get('source', None)
    if request.method == 'POST':
        logger.debug("Rozpoczęcie logowania użytkownika")
        form = LogInForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)

            if user:
                login(request, user)
                logger.info(f"Użytkownik zalogowany: {username}", )

                if source == 'koszyk':
                    return redirect('/koszyk/')
                else:
                    messages.success(request, 'Zalogowano.')
                    return redirect('home')
            else:
                logger.warning(f"Nieudane logowanie dla użytkownika: {username}")
                messages.error(request, 'Nieprawidłowe dane. Podaj prawidłowy login oraz hasło.')

    else:
        form = LogInForm()
    return render(request, 'logowanie.html', {'form': form})


def user_logout(request):
    """
    Wylogowanie użytkownika.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    """
    logout(request)
    logger.info(f"Użytkownik wylogowany")
    messages.success(request, "Wylogowano")

    return redirect("/login/")


def privacy_policy(request):
    """
    Widok polityki prywatności.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    """
    logger.debug("Wyświetlenie polityki prywatności")
    return render(request, 'privacy_policy.html')


def dodaj_do_koszyka_home(request, atrakcja_id):
    """
    Dodaje atrakcję do koszyka z widoku home.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    atrakcja_id (int): Identyfikator atrakcji, która ma zostać dodana do koszyka.

    GET: Przekierowuje na stronę logowania jeśli użytkownik nie jest zalogowany.
    POST: Dodaje atrakcję do koszyka lub zwiększa ilość jeśli już jest w koszyku.
    """
    if request.user.is_authenticated:
        logger.debug(f"Rozpoczęcie dodawania do koszyka z widoku home: atrakcja_id={atrakcja_id}")

        atrakcja = get_object_or_404(Atrakcja, pk=atrakcja_id)
        koszyk = Koszyk.objects.filter(id_atrakcji=atrakcja, id_klienta=request.user, cena_koncowa=atrakcja.cena_podstawowa).first()

        if koszyk:
            koszyk.ilosc += 1
            koszyk.save()
            messages.success(request, 'Produkt dodany do koszyka ponownie')
            logger.info(f"Dodano ponownie do koszyka: {atrakcja_id}")
            return redirect(request.META.get('HTTP_REFERER', 'home'))
        else:
            koszyk = Koszyk.objects.create(id_atrakcji=atrakcja, id_klienta=request.user, cena_koncowa=atrakcja.cena_podstawowa)
            koszyk.save()
            messages.success(request, 'Produkt dodano do koszyka')
            logger.info(f"Dodano do koszyka: {atrakcja_id}")
            return redirect(request.META.get('HTTP_REFERER', 'home'))
    else:
        logger.warning(f"Niezalogowany użytkownik próbował dodać do koszyka: {atrakcja_id}")
        return redirect('/login/')

    

def dodaj_do_koszyka(request, atrakcja_id):
    """
    Dodaje atrakcję do koszyka.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    atrakcja_id (int): Identyfikator atrakcji, która ma zostać dodana do koszyka.

    GET: Przekierowuje na stronę logowania jeśli użytkownik nie jest zalogowany.
    POST: Dodaje atrakcję do koszyka lub zmienia ilość już dodanej atrakcji.
    """
    if request.user.is_authenticated:
        atrakcja = get_object_or_404(Atrakcja, pk=atrakcja_id)

        if request.method == 'POST':
            if 'action' in request.POST:
                action = request.POST['action']
                if action == 'increase':
                    koszyk = Koszyk.objects.filter(id_atrakcji=atrakcja, id_klienta=request.user).first()
                    if koszyk:
                        koszyk.ilosc += 1
                        messages.success(request, 'Dodano do koszyka')
                        koszyk.save()
                        logger.info(f"Zwiększono ilość w koszyku: {atrakcja_id}")
                    else:
                        Koszyk.objects.create(id_atrakcji=atrakcja, id_klienta=request.user, cena_koncowa=atrakcja.cena_podstawowa, ilosc=1)
                        logger.info(f"Dodano do koszyka: {atrakcja_id}")
                elif action == 'decrease':
                    koszyk = Koszyk.objects.filter(id_atrakcji=atrakcja, id_klienta=request.user).first()
                    if koszyk and koszyk.ilosc > 1:
                        koszyk.ilosc -= 1
                        koszyk.save()
                        messages.success(request, 'Usunięto z koszyka')
                        logger.info(f"Zmniejszono ilość w koszyku: {atrakcja_id}")
                    elif koszyk and koszyk.ilosc == 1:
                        koszyk.delete()
                        messages.success(request, 'Usunięto atrakcję z koszyka')
                        logger.info(f"Usunięto atrakcję z koszyka: {atrakcja_id}")
            return redirect('koszyk')
    else:
        logger.warning(f"Niezalogowany użytkownik próbował dodać do koszyka: {atrakcja_id}")
        return redirect('/login/')



def usun_z_koszyka(request, item_id):
    """
    Usuwa pozycję z koszyka.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    item_id (int): Identyfikator pozycji w koszyku, która ma zostać usunięta.

    POST: Usuwa wybraną pozycję z koszyka.
    """
    if request.method == 'POST':
        logger.debug(f"Rozpoczęcie usuwania z koszyka: item_id={item_id}")

        item = get_object_or_404(Koszyk, pk=item_id)
        item.delete()

        messages.success(request, 'Usunięto atrakcję z koszyka')
        logger.info(f"Usunięto atrakcję z koszyka: {item_id}")
    return redirect('koszyk')



def trasa(request):
    """
    Generuje trasę zwiedzania.

    GET: Wyświetla formularz do wyboru lokalizacji początkowej i trybu podróży.
    POST: Generuje trasę na podstawie wybranych atrakcji i lokalizacji początkowej.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    """
    if request.method == 'POST':
        logger.debug("Rozpoczęcie generowania trasy")
        form = StartLocation(request.POST)

        if form.is_valid():
            start_loc = form.cleaned_data['start_location']
            koszyk_items = Koszyk.objects.filter(id_klienta=request.user)
            loc_list = [item.id_atrakcji for item in koszyk_items]
            mode = form.cleaned_data['mode']

            static_url, places = generate_static_map(start_loc, loc_list, mode=mode)
            interactive_url = generate_interactive_map(start_loc, loc_list, mode=mode)
            logger.info("Trasy zakończone")

            return render(request, 'trasa.html', {'form': form, 'places': places, 'static_url': static_url, 'interactive_url': interactive_url, 'start_loc': start_loc, 'mode': mode})
    else:
        form = StartLocation()
    return render(request, 'trasa.html', {'form': form})


def pojedynczy_plan(request, plan_id):
    """
    Wyświetla pojedynczy plan podróży.

    GET: Wyświetla informacje o planie oraz formularz do wyboru lokalizacji początkowej i trybu podróży.
    POST: Generuje trasę dla wybranego planu na podstawie lokalizacji początkowej.

    Argumenty:
    request (HttpRequest): Obiekt żądania HTTP.
    plan_id (int): Identyfikator planu, który ma być wyświetlony.
    """
    plan = get_object_or_404(Plan, pk=plan_id)
    atrakcje = plan.atrakcje.all()
    obrazy = [atrakcja.obraz.split(";")[0] for atrakcja in atrakcje]

    if request.method == 'POST':
        form = StartLocation(request.POST)

        if form.is_valid():
            mode = form.cleaned_data['mode']
            start_loc = form.cleaned_data['start_location']
            static_url, places = generate_static_map(start_loc, atrakcje, mode=mode)

            logger.info("Generowanie trasy dla planu zakończone.")

przewodnik_po_miescie/mainapp/templates/atrakcja.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/atrakcja.css' %}">
    <div class="atrakcja">
        <img src="{{ pierwszy_obraz }}" alt="photo" id="obraz">
        <h2 id="nazwa_atrakcji">{{ atrakcja.nazwa_atrakcji }}</h2>
        <div class="opis">
            <h2><b>Opis:</b></h2>
            <p>{{ atrakcja.opis }}</p>
        </div>
        <div class="info">
            <p><b>Kategoria atrakcji:</b> {{ atrakcja.kategoria }}</p>
            <p><b>Cena:</b> {{ atrakcja.cena_podstawowa }} zł</p>
            <p><b>Wiek wstępu:</b> {{ atrakcja.wiek_min }} - {{ atrakcja.wiek_max }} lat</p>
            <p><b>Godziny otwarcia:</b> {{ atrakcja.godzina_otwarcia }} - {{ atrakcja.godzina_zamkniecia }}</p>
            <p><b>Przewidywany czas na zwiedzanie:</b> {{ atrakcja.czas_na_zwiedzanie }} h</p>
        </div>
    </div>
{% endblock %}

przewodnik_po_miescie/mainapp/templates/base.html
<!DOCTYPE html>
<html lang="pl">
{% load static %}
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <title>Atrakcje</title>
    <link rel="stylesheet" href="{% static 'css/powiadomienia.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
<div class="naglowek">
    <a href="{% url 'home' %}">
        <img src="{% static 'global_photos/logo.png' %}" alt="photo">
    </a>
    <div>
        {% if user.is_authenticated %}
        <a href="{% url 'plan_uzytkownika' %}"><div class="zarejestruj"><b>{{ user.username }}</b></div></a>
            <a href="{% url 'logout' %}">
                <div class="zarejestruj"><b>Wyloguj</b></div>
            </a>
            <a href="{%  url 'koszyk' %}">
                <div class="koszyk"><b>Przejdź do koszyka</b></div>
            </a>
        {% else %}
            <a href="{% url 'login' %}">
                <div class="zaloguj"><b>Zaloguj</b></div>
            </a>
            <a href="{% url 'signup' %}">
                <div class="zarejestruj"><b>Zarejestruj</b></div>
            </a>
            <a href="{% url 'login' %}?source=koszyk">
                <div class="koszyk"><b>Przejdź do koszyka</b></div>
            </a>
        {% endif %}
    </div>
</div>

{% block content %}
{% endblock %}

<footer class="footer">
    <div class="footer-content">
        <p>&copy; 2024 Atrakcje. Wszelkie prawa zastrzeżone.</p>
        <p>Kontakt: kontakt@atrakcje.pl | Telefon: 123-456-789</p>
        <p><a href="{% url 'privacy_policy' %}">Polityka prywatności</a></p>
    </div>
</footer>
</body>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'js/base.js' %}"></script>

</html>

przewodnik_po_miescie/mainapp/templates/logowanie.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/logowanie.css' %}">
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    <a href="{% url 'signup' %}">Stwórz konto</a>
</form>

{% endblock %}

przewodnik_po_miescie/mainapp/templates/plany.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/plany.css' %}">
    {% for plan, photo in plans_with_photos %}
    <div class="atrakcja">
        <div class="image-container">
            <a href="{% url 'pojedynczy_plan' plan_id=plan.pk %}">
                <img src="{% static 'plan_photos/' %}{{ photo }}" alt="photo" class="obraz" id="obraz-planu-{{ forloop.counter }}">
            </a>
        </div>
    </div>
    {% endfor %}
{% endblock %}

przewodnik_po_miescie/mainapp/templates/pojedynczy_plan.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/pojedynczy_plan.css' %}">

    <div class="plan" data-plan-nazwa="{{ plan.nazwa_planu }}" data-plan-opis="{{ plan.opis_planu }}">
        {% for atrakcja, obraz in obrazy %}
            <div class="atrakcja" data-nazwa="{{ atrakcja.nazwa_atrakcji }}" data-opis="{{ atrakcja.opis }}" data-obraz="{{ obraz }}"></div>
        {% endfor %}

        <div class="lewa_strona">
            <button class="prev" id="prevButton" data-length="{{ plan.atrakcje.all|length }}">&#10094;</button>
            <img src="{{ obrazy.0 }}" alt="photo" id="obraz-atrakcji" style="width: 700px; height: 550px; text-align: center">
            <button class="next" id="nextButton" data-length="{{ plan.atrakcje.all|length }}">&#10095;</button>
            <p id="nazwa_atrakcji"><b>{{ plan.atrakcje.first.nazwa_atrakcji }}</b></p>
            <p id="opis_atrakcji">{{ plan.atrakcje.first.opis }}</p>
        </div>

        <div class="prawa_strona">
            <p id="nazwa_planu" style="font-size: 40px; text-align: center">{{ plan.nazwa_planu }}</p>
            <p id="opis_planu" style="font-size: 20px">{{ plan.opis_planu }}</p>
            <br><br>
            <form method="POST" id="form1">
                {% csrf_token %}
                <label for="id_start_location"><b>Wprowadź początkową lokalizację</b></label>
                {{ form.start_location }}
                <label for="id_mode"><b>Wybierz sposób podróży</b></label>
                {{ form.mode }}
                <button type="submit" style="margin-top: 5%">Zatwierdź</button>
            </form>
            {% if url %}
                <div class="map-container">
                    <img src="{{ url }}" style="width: 90%; margin-left: 5%">
                    <div>
                            <ul>
                                {% for nr, nazwa in places.items %}
                                    <li>{{ nr }}: {{ nazwa }}</li>
                                {% endfor %}
                            </ul>
                    </div>
                    <form action="{% url 'pdf_download' %}" method="get">
                        <input type="hidden" name="from_basket" value="False">
                        <input type="hidden" name="start_loc" value="{{ start_loc }}">
                        <input type="hidden" name="plan_id" value={{ plan_id }}>
                        <input type="hidden" name="mode" value="{{ mode }}">
                        <button type="submit" id="przycisk">Pobierz plan</button>
                    </form>

                    <form action="{% url 'send_mail' %}" method="get">
                        <input type="hidden" name="from_basket" value="False">
                        <input type="hidden" name="start_loc" value="{{ start_loc }}">
                        <input type="hidden" name="plan_id" value={{ plan_id }}>
                        <input type="hidden" name="mode" value="{{ mode }}">
                        <button type="submit" class="download-button">Wyślij plan mailem</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>

    <script src="{% static 'js/pojedynczy_plan.js' %}"></script>

{% endblock %}

przewodnik_po_miescie/mainapp/templates/privacy_policy.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Polityka prywatności</h1>
    <p>Nasza polityka prywatności jest prosta: nie zbieramy ani nie przechowujemy twoich danych, ani nie śledzimy cię w żaden sposób. Używamy wyłącznie ciasteczek koniecznych do obsługi tej strony.</p>


{% endblock %}

przewodnik_po_miescie/mainapp/templates/rejestracja.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'css/rejestracja.css' %}">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Zarejestruj</button>
    <a href="{% url 'login' %}" id="mam_konto">Masz już konto?</a>
</form>
{% endblock %}

przewodnik_po_miescie/mainapp/templates/trasa.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'css/trasa.css' %}">

<form method="POST" id="form1">
    {% csrf_token %}
    <label for="id_start_location"><b>Wprowadź początkową lokalizację</b></label>
    {{ form.start_location }}
    <label for="id_mode"><b>Wybierz sposób podróży</b></label>
    {{ form.mode }}
    <button type="submit" style="margin-top: 5%">Zatwierdź</button>
</form>

{% if static_url and interactive_url %}
    <div class="map-container first">
        <img src="{{ static_url }}" height="100%" width="100%">
    </div>

    <div class="map-container second">
        <iframe
            width="100%"
            height="100%"
            frameborder="0" style="border:0"
            referrerpolicy="no-referrer-when-downgrade"
            src="{{ interactive_url }}"
            allowfullscreen>
        </iframe>
    </div>
    <div style="margin-top: 50%;">
        <table>
          <thead>
            <tr>
              <th >Znacznik</th>
              <th>Nazwa</th>
            </tr>
          </thead>
          <tbody>
            {% for nr, nazwa in places.items %}
            <tr>
              <td>{{ nr }}</td>
              <td>{{ nazwa }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
    </div>
{% endif %}

{% if static_url %}
    <form action="{% url 'pdf_download' %}" method="get">
        <input type="hidden" name="from_basket" value="True">
        <input type="hidden" name="start_loc" value="{{ start_loc }}">
        <input type="hidden" name="mode" value="{{ mode }}">
        <button type="submit" class="download-button">Pobierz plan</button>
    </form>
    <form action="{% url 'send_mail' %}" method="get">
        <input type="hidden" name="from_basket" value="True">
        <input type="hidden" name="start_loc" value="{{ start_loc }}">
        <input type="hidden" name="mode" value="{{ mode }}">
        <button type="submit" class="download-button">Wyślij plan mailem</button>
    </form>
{% endif %}

{% endblock %}